on:
  schedule:
    # Note the timezone is UTC
    - cron: "0 8 * * *"
  workflow_dispatch:  # this is for manually trigger workflow

jobs:
  track-stars:
    runs-on: ubuntu-latest
    defaults:
      # docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
      run:
        working-directory: ./main
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      # checkout multiple repos: https://github.com/actions/checkout#checkout-multiple-repos-side-by-side
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: cjc7373/my_scripts
          path: my_scripts

      # note github runners have python pre-installed
      # for Ubuntu 22.04, the python version is 3.10
      # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      - name: install dependencies
        run: pip install requests

      - name: run tracking stars script
        run: python ../my_scripts/active/track_stars.py

      # See: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      # Note we need to enable workflow write permission in the repo settings
      - name: commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "daily update"
          git push
